### ISSUE TITLE
Problems when try build

### ISSUE THREAD

**Issue by paulocoutinhox** [simonvanderveldt/docker-buildroot#1]
Hi,

Im trying make a docker image with buildroot to make a image to my raspberry3, but im getting error:

```
PKG_CONFIG_PATH="" make CC="/usr/bin/gcc" HOSTCC="/usr/bin/gcc" \
    obj=/buildroot/output/build/buildroot-config -C support/kconfig -f Makefile.br conf
make[1]: Entering directory '/buildroot/support/kconfig'
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/buildroot/output/build/buildroot-config -DCONFIG_=\"\"  -MM *.c > /buildroot/output/build/buildroot-config/.depend 2>/dev/null || :
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/buildroot/output/build/buildroot-config -DCONFIG_=\"\"   -c conf.c -o /buildroot/output/build/buildroot-config/conf.o
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/buildroot/output/build/buildroot-config -DCONFIG_=\"\"  -I. -c /buildroot/output/build/buildroot-config/zconf.tab.c -o /buildroot/output/build/buildroot-config/zconf.tab.o
/usr/bin/gcc -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/buildroot/output/build/buildroot-config -DCONFIG_=\"\"   /buildroot/output/build/buildroot-config/conf.o /buildroot/output/build/buildroot-config/zconf.tab.o  -o /buildroot/output/build/buildroot-config/conf
rm /buildroot/output/build/buildroot-config/zconf.tab.c
make[1]: Leaving directory '/buildroot/support/kconfig'
#
# configuration written to /buildroot/.config
#
/usr/bin/make -j1 O=/buildroot/output HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" silentoldconfig
make[1]: Entering directory '/buildroot'

*** Error during update of the configuration.

Makefile:911: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 1
make[1]: Leaving directory '/buildroot'
Makefile:550: recipe for target '/buildroot/output/build/buildroot-config/auto.conf' failed
make: *** [/buildroot/output/build/buildroot-config/auto.conf] Error 2
make: *** [run] Error 2
```

Can you help me?

My project is located in:

https://github.com/prsolucoes/docker-buildroot

And the commands are:

> make build
> make run cmd="make raspberrypi3_defconfig; make"

Thanks.

**Comment by simonvanderveldt** [comment]
@prsolucoes sorry, I missed this issue somehow.

What was the exact command you were using? As long as you just run the existing image with a volume mount as described in the readme it should work.

**Comment by simonvanderveldt** [comment]
This happens when simply running `make menuconfig` (or `make somedefconfig`) followed by `make`.
I've managed to circumvent this by editing the main buildroot `Makefile` and changing `silentoldconfig` into just `oldconfig` here https://github.com/buildroot/buildroot/blob/2017.11.2/Makefile#L550
No clue why this is happening yet and the people in #buildroot IRC didn't know it either.
Some more digging will be required...

**Comment by simonvanderveldt** [comment]
I can no longer reproduce this so I'm going to close this issue. In case it's still relevant/you're still running into this issue feel free to reopen it and post some more info.
I've just updated the image to 2018.11.2 so give that one a try if you want :)
